src/buza/urls.py
import django.contrib.auth.urls
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path

from buza import views


urlpatterns = [

    # social-auth-app-django
    url(r'^login/', include('social_django.urls', namespace='social')),

    url(r'about/privacy/', views.PrivacyPolicyView.as_view(), name='privacy-policy'),
    url(r'about/tos/', views.TermsOfService.as_view(), name='terms-of-service'),
    # Django auth
    path('auth/', include(django.contrib.auth.urls)),

    path('', views.HomePageView.as_view(), name='home'),

    # user related paths
    url(r'^register/$', views.register, name='register'),
    path(r'users/<int:pk>/update/', views.UserUpdate.as_view(), name='user-update'),
    path(r'users/<int:pk>/', views.UserDetail.as_view(), name='user-detail'),

    # subject related paths
    path('subjects/<int:pk>/', views.SubjectDetail.as_view(), name='subject-detail'),

    # question related paths
    path('questions/', views.QuestionList.as_view(), name='question-list'),
    path('questions/<int:pk>/', views.QuestionDetail.as_view(), name='question-detail'),
    path(
        'questions/<int:subject_pk>/ask/',
        views.QuestionCreate.as_view(),
        name='question-create',
    ),
    path(
        'questions/<int:pk>/edit/',
        views.QuestionUpdate.as_view(),
        name='question-update',
    ),

    # answer related paths
    path(
        'answers/<int:pk>/edit/',
        views.AnswerUpdate.as_view(),
        name='answer-update',
    ),
    path(
        'questions/<int:question_pk>/answer/',
        views.AnswerCreate.as_view(),
        name='answer-create',
    ),
    # Django admin
    url(r'^admin/', admin.site.urls),

]

src/buza/models.py
from functools import partial
from typing import Union

from django.contrib.auth.models import AbstractUser, AnonymousUser
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.translation import ugettext_lazy as _


# Shortcuts:
_CharField = partial(models.CharField, max_length=1024)


class TimestampedModel(models.Model):
    """
    Base class with `created` and `modified` fields.
    """
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    modified = models.DateTimeField(auto_now=True, db_index=True)

    class Meta:
        abstract = True


class Subject(models.Model):
    title = _CharField()
    short_title = models.TextField()
    description = models.TextField()

    def __str__(self) -> str:
        return str(self.title)


class User(AbstractUser):

    # Authentication fields
    phone = models.CharField(
        _('phone number'),
        blank=True,
        max_length=11,
    )

    # School fields
    school = models.CharField(_('school name'), blank=True, null=True, max_length=100)
    school_address = models.CharField(
        _('school address'),
        blank=True, null=True,
        max_length=300,
    )
    grade = models.IntegerField(blank=True, null=True, default=7)

    # Personal fields
    photo = models.ImageField(_('profile photo'),
                              upload_to='users/%Y/%m/%d',
                              blank=True)
    bio = models.CharField(blank=True, null=True, max_length=250)

    subjects = models.ManyToManyField(Subject)

    def __str__(self) -> str:
        return str(self.username)


#: Helper type for Django request users: either anonymous or signed-in.
RequestUser = Union[AnonymousUser, User]


class Question(TimestampedModel, models.Model):

    author = models.ForeignKey(User, on_delete=models.PROTECT)

    title = _CharField(
        verbose_name='Question Summary',
        help_text='Write a short sentence summarising your question',
    )
    body = models.TextField(
        blank=True,
        verbose_name='Question Description',
        help_text='Give a detailed description of your question')
    subject = models.ForeignKey(Subject, on_delete=models.PROTECT)
    grade = models.IntegerField(
        validators=[MinValueValidator(7), MaxValueValidator(12)],
        help_text="Which grade it this question most relevant for? "
                  "By default this will be the grade that you are in.",
    )

    def __str__(self) -> str:
        return f'By {self.author}: {self.title}'


class Answer(TimestampedModel, models.Model):

    author = models.ForeignKey(User, on_delete=models.PROTECT)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    body = models.TextField()

    def __str__(self) -> str:
        question: Question = self.question
        return f'By {self.author} to question {question.pk}: {question.title}'

src/buza/templates/buza/answer_form.html
{% extends 'base.html' %}
{% comment %}
Expected context:

* question: The question being answered

{% endcomment %}
{% load static %}

{% block head_extra %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'buza/css/questions.css' %}">
{% endblock %}

{% block title %}Answer question - {{ block.super }}{% endblock %}

{% block content %}

    {% include 'includes/question_card_full.html' with question=question only %}

    <form method="post" action=
            "{% if answer.pk %} {% url 'answer-update' pk=answer.pk %}
            {% else %}
            {% url 'answer-create' question_pk=question.pk %}
            {% endif %}">  {# FIXME #}
        {% csrf_token %}
        {{ form.as_p }}
        <p>
            <input type="submit" value="{% if answer.pk %}Update answer {% else %} Answer{% endif %}">
        </p>
    </form>

{% endblock %}

src/buza/templates/buza/my_subjects_view.html
{% extends 'base.html' %}

{% block title %}Subjects - {{ block.super }}{% endblock %}

{% block content %}
    <h1>Joined Subjects</h1>
        <div style="padding-bottom: 2%; position: center;box-sizing: border-box;">
        {% if user.is_authenticated %}
        <a href="{% url 'my-subject-list' pk=user.pk%}" style="background-color: silver; padding: 1%;font-weight: bold; border-radius: 10%;">
        My Subjects </a>
        <a href="{% url 'subject-list' %}" style="background-color: lightyellow; padding: 1%;font-weight: bold; border-radius: 10%;">
        All Subjects </a>
            {% endif %}
    </div>
    {% for subject in user.subjects.all %}
        <div class="question">

            <a href="{% url 'subject-detail' subject.pk %}" class="question-title">
                {{ subject.title }}
            </a>
        <div style="clear: both"></div>
    {% endfor %}
{% endblock %}

src/buza/templates/buza/question_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block head_extra %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'buza/css/questions.css' %}">
{% endblock %}

{% block title %}{{ question.title }} - {{ block.super }}{% endblock %}

{% block content %}
    {% include 'includes/question_card_full.html' with question=question user=user only %}
<br>
    {% with answers=question.answer_set.all %}  {# TODO: Ordering #}
        {% if answers %}
            <h5 class="question__answers_heading">Answers</h5>
    <div class="d-flex justify-content-center">
        <span class="dot mr-2"></span>
        <span class="dot ml-2"></span>
        <span class="dot ml-2"></span>
    </div>
            {% for answer in question.answer_set.all %}
               <div class=" card question__card mx-auto table-hover">
    <div class="question__card-header d-flex justify-content-between buza-purple_text">
                        <a href="{% url 'user-detail' question.author.pk %}">
            @{{ answer.author.username }}</a>
        <p class="date question__attribution buza-grey_text">
            {{ answer.modified | naturaltime}}</p>
  </div>
    <div class="question__body">
        {{ answer.body}}
            {% if user == answer.author %}
              <p class="flex-grow-1">
                  <a href="{% url 'answer-update' pk=answer.pk %}" class="d-inline-block question__edit_answer">
                                    Edit answer
                  </a>
              </p>
                        {% endif %}
    </div></div>
            {% endfor %}
        {% else %}
            <h2 class="question__answers_heading">No answers yet</h2>
    <div class="d-flex justify-content-center">
        <span class="dot mr-2"></span>
        <span class="dot ml-2"></span>
        <span class="dot ml-2"></span>
    </div>
        {% endif %}
    {% endwith %}

    <div class="justify-content-center">
        <a href="{% url 'answer-create' question_pk=question.pk %}" class="d-inline-block question__add_answer justify-content-center">
           Add your answer
        </a>
    </div>
{% endblock %}

src/buza/templates/buza/question_form.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block head_extra %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'buza/css/questions.css' %}">
{% endblock %}

{% block title %}Ask a question - {{ block.super }}{% endblock %}

{% block content %}
<div class="text-center mx-auto my-5" style="max-width: 40em">

    <h2>{% if question.pk %}Edit{% else %}Add a new{% endif %} Question</h2>

    {% crispy form %}

</div>
{% endblock %}

src/buza/templates/buza/question_list.html
{% extends 'base.html' %}
{% load static %}

{% block head_extra %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'buza/css/questions.css' %}">
    <link rel="stylesheet" href="{% static 'buza/css/subjects.css' %}">
{% endblock %}

{% block title %}Questions - {{ block.super }}{% endblock %}

{% block content %}
 <div class="subject_detail-container">
<div  class="subject__deck">
    {% for subject in subject_list %}
        {% include 'includes/subject_cards.html' with subject=subject user=user csrf_token=csrf_token only%}
    {% endfor %}
</div>
 <div class="subject__question_list">
    {% for question in question_list %}
        {% include 'includes/question_card_brief.html' with question=question only %}
    {% endfor %}
 </div>
 </div>
{% endblock %}

src/buza/templates/buza/subject_detail.html
{% extends 'base.html' %}
{% load static %}

{% block head_extra %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'buza/css/subjects.css' %}">
    <link rel="stylesheet" href="{% static 'buza/css/questions.css' %}">
{% endblock %}

{% block title %}{{ subject.title }} - {{ block.super }}{% endblock %}

{% block content %}
    <div class="subject_detail-container">
        <div id="react" class="subject__deck">
           {% for view_subject in subject_list %}
                 {% include 'includes/subject_cards.html' with subject=view_subject user=user csrf_token=csrf_token selected_subject=subject only%}
            {% endfor %}
        </div>
        <div class="subject__question_list">
                <span class="btn__new_question">
                    <a href="{% url 'question-create' subject_pk=subject.pk%}" class="btn btn-primary btn-buza-green">
                    Ask New {{subject.short_title}} Question
                    </a>
                </span>
            {% with questions=subject.question_set.all %}
                {% if questions %}
                    {% for question in questions %}
                        {% include 'includes/question_card_brief.html' with question=question only %}
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>
    </div>

    <script>
        window.props = {% autoescape off %}{{ props }}{% endautoescape %};
        window.reactEntrypoint = document.getElementById('react');
    </script>
    <script type="text/javascript" src="{% static "components/SubjectCards.js" %}"></script>
{% endblock %}

src/buza/templates/buza/user_detail.html
{% extends 'base.html' %}
{% load static %}

{% block head_extra %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'buza/css/questions.css' %}">
    <link rel="stylesheet" href="{% static 'buza/css/subjects.css' %}">
{% endblock %}

{% block title %}{{ user_object.get_full_name }} - {{ block.super }}{% endblock %}

{% block content %}
    <div class="text-center">

        {# Show account actions for the signed-in user. #}
        {% if user_object == user %}
            <p>
                <a class="btn btn-info btn-sm" href="{% url 'user-update' pk=user_object.pk %}">Edit Account</a>
                <a class="btn btn-outline-info btn-sm" href="{% url 'password_change' %}">Change Password</a>
                <a class="btn btn-outline-danger btn-sm" href="{% url 'logout' %}">Log out</a>
            </p>
        {% endif %}

        <h1>{{ user_object.get_full_name }}</h1>

        <p>
            <a href="{% url 'user-detail' user_object.pk %}">
                @{{ user_object.username }}
            </a>
        </p>

        {% if user_object.bio %}
            <p>{{ user_object.bio }}</p>
        {% endif %}
    </div>

    {# TODO (Pi 2019-02-10): Show the user's activity stream here, once we have that. #}

    {# get all the questions that the user has asked #}
    <div>
        {% for question in user_object.question_set.all %}
            {% include 'includes/question_card_brief.html' with question=question only %}
        {% endfor %}
    </div>

{% endblock %}

src/buza/templates/buza/user_form.html
{% extends "base.html" %}

{% block title %}Create an account{% endblock %}
{% block content %}
<h1>Create an Buza account</h1>
<p>Please, sign up using the following form</p>

<form action="." method="post">
	{{form}}
	{% csrf_token%}
	<p><input type="submit" value="Create my account"></p>

</form>
{% endblock %}